// Reading the stamp that scripts/build-info.js leaves behind.
//
// Everything here is pure except `read`, so the formatting can be tested
// without Electron and without a packaged app, same split as src/cache.js.
//
// The file is absent in a source run (`npm start`, `node --test`), and that is
// a normal state rather than an error: an app running from the working tree has
// no single commit to claim. It says so instead of guessing.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// What a version IS and how its release reads are core's to decide; this module
// only formats the stamp for a person. `channelOf` is the one owner of which
// prerelease identifier is the channel, so the version a reader sees reads its
// channel through the same function the update check does.
import { parse, format } from '../../core/version.js';
import { channelOf } from '../../core/updates.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));

// Ten hex digits. Seven is git's traditional abbreviation and GitHub's display
// width, but it is short enough to collide in a repo of any size, and this
// string's whole job is to identify one build unambiguously.
export const SHORT_LENGTH = 10;

const UNKNOWN = { commit: null, shortCommit: null, branch: null, dirty: false, count: null, builtAt: null };

/**
 * Coerce whatever was on disk into the shape the rest of the app expects.
 *
 * Tolerant on purpose: this file is generated by a build hook, and a truncated
 * or hand-edited copy must degrade to "source build" rather than take the
 * settings page down with it.
 *
 * @param {unknown} raw
 * @returns {{commit: string|null, shortCommit: string|null, branch: string|null, dirty: boolean, count: number|null, builtAt: string|null}}
 */
export function normalize(raw) {
  if (!raw || typeof raw !== 'object') return { ...UNKNOWN };
  // A commit is 40 hex characters. Anything else, a branch name, a truncated
  // write, a placeholder, is not one, and half a hash is worse than none.
  const commit = typeof raw.commit === 'string' && /^[0-9a-f]{40}$/i.test(raw.commit)
    ? raw.commit.toLowerCase()
    : null;
  return {
    commit,
    shortCommit: commit ? commit.slice(0, SHORT_LENGTH) : null,
    branch: typeof raw.branch === 'string' && raw.branch ? raw.branch : null,
    dirty: raw.dirty === true,
    // The build number, a positive integer or nothing. A string, a zero or a
    // fraction is a truncated or hand-edited stamp, and a build number that
    // lies about which build this is would be worse than one that is absent.
    count: Number.isInteger(raw.count) && raw.count > 0 ? raw.count : null,
    builtAt: typeof raw.builtAt === 'string' && raw.builtAt ? raw.builtAt : null,
  };
}

/**
 * The stamp for this build, or the unknown shape when running from source.
 *
 * @param {string} [file]  Override, for tests.
 */
export function read(file = path.join(HERE, 'build-info.json')) {
  try {
    return normalize(JSON.parse(fs.readFileSync(file, 'utf8')));
  } catch {
    return { ...UNKNOWN };
  }
}

/** `2026-09-02T08:41:07Z` -> `2026-09-02 08:41Z`, or null for anything else. */
export function formatBuiltAt(builtAt) {
  const match = /^(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2})/.exec(builtAt || '');
  return match ? `${match[1]} ${match[2]}Z` : null;
}

/**
 * The version a person reads: the release and its channel, with the build and
 * commit tail removed.
 *
 *   `0.0.1-dev.383.59f34d85a8` -> `0.0.1-dev`
 *   `1.0.1`                    -> `1.0.1`
 *
 * The full string is the BUILD version, and it has to stay whole. It is what
 * electron-builder stamps as `app.getVersion()`, what `artifactName`
 * interpolates into every installer filename, and what the update check ranks;
 * the count is what makes one dev build order above the next and the sha is
 * what names the exact code, so neither can be dropped without losing ordering
 * or an installer's identity. See scripts/version.js for that argument in full.
 *
 * What a person READS is the front of it: the release and its channel. The
 * count and the commit are shown on About as rows of their own (see
 * `identityFields`) instead of being welded into the version here.
 *
 * The first prerelease identifier is the channel -- `channelOf` reads the same
 * one -- so it stays: `-dev` is what tells a reader, and the client-context
 * block, that this is not a stable build. An unreadable string is returned
 * unchanged rather than dressed up as a version, since inventing one for
 * something that is not a version would be worse than showing what arrived.
 *
 * @param {string} version  the build version, from app.getVersion()
 */
export function readableVersion(version) {
  const parsed = parse(version);
  if (!parsed) return version == null ? '' : String(version);
  return format({
    major: parsed.major,
    minor: parsed.minor,
    patch: parsed.patch,
    prerelease: channelOf(version),
  });
}

/**
 * The build's identity as About's own rows: which commit, how many commits in,
 * when it was built, and the branch when it is not `main`.
 *
 * A `{ label, value }` per row, the shape the shared page draws, so the host
 * hands them straight over and the page keeps holding no formatting of its own.
 * This is where the count and the commit live now that the version string does
 * not carry them.
 *
 * Nothing is invented for a field the stamp does not have: a source run (no
 * stamp at all) has no commit to claim, so it shows no rows, and a shallow
 * checkout with no count shows a commit row without a build row. That honesty
 * is the point of the stamp rather than a gap in it.
 *
 * The branch is named only when it is not `main`, because on `main` it is noise
 * and off it, it is the single most useful thing on the row.
 *
 * @param {ReturnType<typeof normalize>} info
 * @returns {Array<{label: string, value: string}>}
 */
export function identityFields(info) {
  const stamp = normalize(info);
  if (!stamp.commit) return [];

  const sha = stamp.dirty ? `${stamp.shortCommit}-dirty` : stamp.shortCommit;
  const built = formatBuiltAt(stamp.builtAt);
  return [
    { label: 'Commit', value: sha },
    ...(stamp.count ? [{ label: 'Build', value: String(stamp.count) }] : []),
    ...(built ? [{ label: 'Built', value: built }] : []),
    ...(stamp.branch && stamp.branch !== 'main' ? [{ label: 'Branch', value: stamp.branch }] : []),
  ];
}

/**
 * A value identifying this build for the cache-clearing check, or null.
 *
 * Null for a dirty tree on purpose. Two different dirty builds of the same
 * commit share a hash, so trusting it there would stop detecting upgrades
 * during exactly the work most likely to need them; the caller falls back to
 * the bundle's size and mtime, which do move. See cache.buildFingerprint.
 */
export function buildId(info) {
  const stamp = normalize(info);
  return stamp.commit && !stamp.dirty ? stamp.commit : null;
}
